version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: "index.html"
    owner: apache
    group: apache
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: /deregister_from_elb
    - location: scripts/webserver-stop.sh
    - location: /delete-old-index.sh
  AfterInstall:
    #- location: scripts/sleep.sh
    - location: scripts/webserver-start.sh
    - location: /register_with_elb
